"""add_assigner_id_to_tasks_and_jobs

Revision ID: 0588b75e0f7b
Revises: 19e7fac005e5
Create Date: 2025-10-06 16:34:13.778181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0588b75e0f7b'
down_revision = '19e7fac005e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_check_in', table_name='attendance')
    op.drop_index('ix_attendance_check_out', table_name='attendance')
    op.drop_index('ix_attendance_created_at', table_name='attendance')
    op.drop_index('ix_attendance_date_status', table_name='attendance')
    op.drop_index('ix_attendance_updated_at', table_name='attendance')
    op.drop_index('ix_efficiency_scores_period', table_name='efficiency_scores')
    op.drop_index('ix_efficiency_scores_team_period', table_name='efficiency_scores')
    op.drop_index('ix_efficiency_scores_user_period', table_name='efficiency_scores')
    op.drop_index('ix_invoices_created_at', table_name='invoices')
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.drop_index('ix_invoices_status_due_date', table_name='invoices')
    op.drop_index('ix_invoices_updated_at', table_name='invoices')
    op.add_column('jobs', sa.Column('assigner_id', sa.Integer(), nullable=True))
    op.drop_index('ix_jobs_client', table_name='jobs')
    op.drop_index('ix_jobs_created_at', table_name='jobs')
    op.drop_index('ix_jobs_status_progress', table_name='jobs')
    op.drop_index('ix_jobs_updated_at', table_name='jobs')
    op.create_index('ix_jobs_assigner', 'jobs', ['assigner_id'], unique=False)
    op.create_index(op.f('ix_jobs_assigner_id'), 'jobs', ['assigner_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'users', ['assigner_id'], ['id'])
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_notifications_read_at', table_name='notifications')
    op.drop_index('ix_notifications_type_status', table_name='notifications')
    op.drop_index('ix_notifications_user_status', table_name='notifications')
    op.drop_index('ix_performance_metrics_created_at', table_name='performance_metrics')
    op.drop_index('ix_performance_metrics_period', table_name='performance_metrics')
    op.drop_index('ix_performance_metrics_team_period', table_name='performance_metrics')
    op.drop_index('ix_performance_metrics_user_period', table_name='performance_metrics')
    op.drop_index('ix_reminders_created_at', table_name='reminders')
    op.drop_index('ix_reminders_scheduled_at', table_name='reminders')
    op.drop_index('ix_reminders_status', table_name='reminders')
    op.drop_index('ix_reminders_user_type', table_name='reminders')
    op.add_column('tasks', sa.Column('assigner_id', sa.Integer(), nullable=True))
    op.drop_index('ix_tasks_created_at', table_name='tasks')
    op.drop_index('ix_tasks_job_id_status', table_name='tasks')
    op.drop_index('ix_tasks_priority_status', table_name='tasks')
    op.drop_index('ix_tasks_status_deadline', table_name='tasks')
    op.drop_index('ix_tasks_updated_at', table_name='tasks')
    op.create_index('ix_tasks_assigner', 'tasks', ['assigner_id'], unique=False)
    op.create_index(op.f('ix_tasks_assigner_id'), 'tasks', ['assigner_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['assigner_id'], ['id'])
    op.drop_index('ix_teams_created_at', table_name='teams')
    op.drop_index('ix_teams_supervisor_id', table_name='teams')
    op.drop_index('ix_teams_updated_at', table_name='teams')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_index('ix_users_updated_at', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_updated_at', 'users', ['updated_at'], unique=False)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('ix_teams_updated_at', 'teams', ['updated_at'], unique=False)
    op.create_index('ix_teams_supervisor_id', 'teams', ['supervisor_id'], unique=False)
    op.create_index('ix_teams_created_at', 'teams', ['created_at'], unique=False)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_assigner_id'), table_name='tasks')
    op.drop_index('ix_tasks_assigner', table_name='tasks')
    op.create_index('ix_tasks_updated_at', 'tasks', ['updated_at'], unique=False)
    op.create_index('ix_tasks_status_deadline', 'tasks', ['status', 'deadline'], unique=False)
    op.create_index('ix_tasks_priority_status', 'tasks', ['priority', 'status'], unique=False)
    op.create_index('ix_tasks_job_id_status', 'tasks', ['job_id', 'status'], unique=False)
    op.create_index('ix_tasks_created_at', 'tasks', ['created_at'], unique=False)
    op.drop_column('tasks', 'assigner_id')
    op.create_index('ix_reminders_user_type', 'reminders', ['user_id', 'type'], unique=False)
    op.create_index('ix_reminders_status', 'reminders', ['status'], unique=False)
    op.create_index('ix_reminders_scheduled_at', 'reminders', ['scheduled_at'], unique=False)
    op.create_index('ix_reminders_created_at', 'reminders', ['created_at'], unique=False)
    op.create_index('ix_performance_metrics_user_period', 'performance_metrics', ['user_id', 'period_start'], unique=False)
    op.create_index('ix_performance_metrics_team_period', 'performance_metrics', ['team_id', 'period_start'], unique=False)
    op.create_index('ix_performance_metrics_period', 'performance_metrics', ['period_start', 'period_end'], unique=False)
    op.create_index('ix_performance_metrics_created_at', 'performance_metrics', ['created_at'], unique=False)
    op.create_index('ix_notifications_user_status', 'notifications', ['user_id', 'status'], unique=False)
    op.create_index('ix_notifications_type_status', 'notifications', ['type', 'status'], unique=False)
    op.create_index('ix_notifications_read_at', 'notifications', ['read_at'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_assigner_id'), table_name='jobs')
    op.drop_index('ix_jobs_assigner', table_name='jobs')
    op.create_index('ix_jobs_updated_at', 'jobs', ['updated_at'], unique=False)
    op.create_index('ix_jobs_status_progress', 'jobs', ['status', 'progress'], unique=False)
    op.create_index('ix_jobs_created_at', 'jobs', ['created_at'], unique=False)
    op.create_index('ix_jobs_client', 'jobs', ['client'], unique=False)
    op.drop_column('jobs', 'assigner_id')
    op.create_index('ix_invoices_updated_at', 'invoices', ['updated_at'], unique=False)
    op.create_index('ix_invoices_status_due_date', 'invoices', ['status', 'due_date'], unique=False)
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=False)
    op.create_index('ix_invoices_created_at', 'invoices', ['created_at'], unique=False)
    op.create_index('ix_efficiency_scores_user_period', 'efficiency_scores', ['user_id', 'period_start'], unique=False)
    op.create_index('ix_efficiency_scores_team_period', 'efficiency_scores', ['team_id', 'period_start'], unique=False)
    op.create_index('ix_efficiency_scores_period', 'efficiency_scores', ['period_start', 'period_end'], unique=False)
    op.create_index('ix_attendance_updated_at', 'attendance', ['updated_at'], unique=False)
    op.create_index('ix_attendance_date_status', 'attendance', ['date', 'status'], unique=False)
    op.create_index('ix_attendance_created_at', 'attendance', ['created_at'], unique=False)
    op.create_index('ix_attendance_check_out', 'attendance', ['check_out'], unique=False)
    op.create_index('ix_attendance_check_in', 'attendance', ['check_in'], unique=False)
    # ### end Alembic commands ###
