"""add_expenses_table

Revision ID: 248ab4098969
Revises: 50875a8f26f9
Create Date: 2025-10-12 12:24:13.156649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248ab4098969'
down_revision = '50875a8f26f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_category'), 'expenses', ['category'], unique=False)
    op.create_index('ix_expenses_category_date', 'expenses', ['category', 'date'], unique=False)
    op.create_index('ix_expenses_created_by_date', 'expenses', ['created_by_id', 'date'], unique=False)
    op.create_index(op.f('ix_expenses_created_by_id'), 'expenses', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_expenses_date'), 'expenses', ['date'], unique=False)
    op.create_index('ix_expenses_date_amount', 'expenses', ['date', 'amount'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index('ix_expenses_date_amount', table_name='expenses')
    op.drop_index(op.f('ix_expenses_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_created_by_id'), table_name='expenses')
    op.drop_index('ix_expenses_created_by_date', table_name='expenses')
    op.drop_index('ix_expenses_category_date', table_name='expenses')
    op.drop_index(op.f('ix_expenses_category'), table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
