"""Remove circular dependency between users and teams

Revision ID: 33989d3eda80
Revises: bae848cb44d7
Create Date: 2025-09-29 13:12:39.113265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33989d3eda80'
down_revision = 'bae848cb44d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teams_supervisor_id_fkey', 'teams', type_='foreignkey')
    op.drop_column('teams', 'supervisor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('supervisor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('teams_supervisor_id_fkey', 'teams', 'users', ['supervisor_id'], ['id'])
    # ### end Alembic commands ###
