"""add_performance_indexes_for_expenses

Revision ID: 3c8fa084d450
Revises: 248ab4098969
Create Date: 2025-10-12 13:03:36.980444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8fa084d450'
down_revision = '248ab4098969'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
