"""add_password_reset_tokens_table

Revision ID: 50875a8f26f9
Revises: 6fc313e09287
Create Date: 2025-10-10 13:34:01.957560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50875a8f26f9'
down_revision = '6fc313e09287'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index('ix_password_reset_tokens_token_used', 'password_reset_tokens', ['token', 'used'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_used'), 'password_reset_tokens', ['used'], unique=False)
    op.create_index('ix_password_reset_tokens_user_expires', 'password_reset_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_tokens_user_expires', table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_used'), table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_tokens_token_used', table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
