"""remove_pdf_path_from_invoices

Revision ID: 6fc313e09287
Revises: 76b67d6db7dc
Create Date: 2025-10-09 12:11:47.961761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc313e09287'
down_revision = '76b67d6db7dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'pdf_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('pdf_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
