"""add_additional_performance_indexes

Revision ID: 76b67d6db7dc
Revises: 827c3be46389
Create Date: 2025-10-06 16:48:50.961005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b67d6db7dc'
down_revision = '827c3be46389'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_jobs_created_at', 'jobs', ['created_at'], unique=False)
    op.create_index('ix_jobs_supervisor_status', 'jobs', ['supervisor_id', 'status'], unique=False)
    op.create_index('ix_tasks_created_at', 'tasks', ['created_at'], unique=False)
    op.create_index('ix_tasks_deadline_status', 'tasks', ['deadline', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_deadline_status', table_name='tasks')
    op.drop_index('ix_tasks_created_at', table_name='tasks')
    op.drop_index('ix_jobs_supervisor_status', table_name='jobs')
    op.drop_index('ix_jobs_created_at', table_name='jobs')
    # ### end Alembic commands ###
