"""add_comprehensive_indexes_for_assigner_fields

Revision ID: 827c3be46389
Revises: 0588b75e0f7b
Create Date: 2025-10-06 16:37:48.427658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827c3be46389'
down_revision = '0588b75e0f7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_jobs_assigner_status', 'jobs', ['assigner_id', 'status'], unique=False)
    op.create_index('ix_jobs_assigner_team', 'jobs', ['assigner_id', 'team_id'], unique=False)
    op.create_index('ix_jobs_supervisor_assigner', 'jobs', ['supervisor_id', 'assigner_id'], unique=False)
    op.create_index('ix_tasks_assigner_assigned', 'tasks', ['assigner_id', 'assigned_to_id'], unique=False)
    op.create_index('ix_tasks_assigner_status', 'tasks', ['assigner_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_assigner_status', table_name='tasks')
    op.drop_index('ix_tasks_assigner_assigned', table_name='tasks')
    op.drop_index('ix_jobs_supervisor_assigner', table_name='jobs')
    op.drop_index('ix_jobs_assigner_team', table_name='jobs')
    op.drop_index('ix_jobs_assigner_status', table_name='jobs')
    # ### end Alembic commands ###
