"""add_job_status_column

Revision ID: 91fb1eb66bf2
Revises: a774acc6155e
Create Date: 2025-09-30 09:28:54.155169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91fb1eb66bf2'
down_revision = 'a774acc6155e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    jobstatus_enum = sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='jobstatus')
    jobstatus_enum.create(op.get_bind())
    
    # Add the column with the enum type
    op.add_column('jobs', sa.Column('status', jobstatus_enum, nullable=True))
    
    # Update existing records to set status based on progress
    op.execute("""
        UPDATE jobs 
        SET status = CASE 
            WHEN progress = 0.0 THEN 'NOT_STARTED'::jobstatus
            WHEN progress = 100.0 THEN 'COMPLETED'::jobstatus
            ELSE 'IN_PROGRESS'::jobstatus
        END
    """)
    
    # Make the column not nullable after setting values
    op.alter_column('jobs', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'status')
    # Drop the enum type
    sa.Enum(name='jobstatus').drop(op.get_bind())
    # ### end Alembic commands ###
