"""add_supervisor_id_to_users

Revision ID: a774acc6155e
Revises: 33989d3eda80
Create Date: 2025-09-29 13:47:03.994854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a774acc6155e'
down_revision = '33989d3eda80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('efficiency_scores', sa.Column('team_id', sa.Integer(), nullable=True))
    op.add_column('efficiency_scores', sa.Column('tasks_completed_on_time', sa.Integer(), nullable=True))
    op.add_column('efficiency_scores', sa.Column('total_tasks_assigned', sa.Integer(), nullable=True))
    op.add_column('efficiency_scores', sa.Column('period_start', sa.Date(), nullable=False))
    op.add_column('efficiency_scores', sa.Column('period_end', sa.Date(), nullable=False))
    op.create_foreign_key(None, 'efficiency_scores', 'teams', ['team_id'], ['id'])
    op.add_column('invoices', sa.Column('invoice_number', sa.String(length=50), nullable=False))
    op.add_column('invoices', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('pdf_path', sa.String(length=500), nullable=True))
    op.create_unique_constraint(None, 'invoices', ['invoice_number'])
    op.add_column('users', sa.Column('supervisor_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('picture_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('contact_info', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['supervisor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'contact_info')
    op.drop_column('users', 'picture_url')
    op.drop_column('users', 'supervisor_id')
    op.drop_constraint(None, 'invoices', type_='unique')
    op.drop_column('invoices', 'pdf_path')
    op.drop_column('invoices', 'description')
    op.drop_column('invoices', 'invoice_number')
    op.drop_constraint(None, 'efficiency_scores', type_='foreignkey')
    op.drop_column('efficiency_scores', 'period_end')
    op.drop_column('efficiency_scores', 'period_start')
    op.drop_column('efficiency_scores', 'total_tasks_assigned')
    op.drop_column('efficiency_scores', 'tasks_completed_on_time')
    op.drop_column('efficiency_scores', 'team_id')
    # ### end Alembic commands ###
