"""rename_assignee_to_assigned_to_in_tasks

Revision ID: b19c859f4022
Revises: 4eeedebc1852
Create Date: 2025-09-30 13:21:06.255332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19c859f4022'
down_revision = '4eeedebc1852'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    op.drop_constraint('tasks_assignee_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to_id'], ['id'])
    op.drop_column('tasks', 'assignee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assignee_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_assignee_id_fkey', 'tasks', 'users', ['assignee_id'], ['id'])
    op.drop_column('tasks', 'assigned_to_id')
    # ### end Alembic commands ###
