"""Fix circular dependency between users and teams

Revision ID: bae848cb44d7
Revises: 65bfc2711002
Create Date: 2025-09-29 13:09:36.117596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae848cb44d7'
down_revision = '65bfc2711002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'supervisor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'supervisor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
