"""add_supervisor_id_to_teams

Revision ID: d7b489969a16
Revises: e838160545c1
Create Date: 2025-09-30 12:18:47.500620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b489969a16'
down_revision = 'e838160545c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('supervisor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teams', 'users', ['supervisor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'supervisor_id')
    # ### end Alembic commands ###
