"""add_phone_number_to_users

Revision ID: e838160545c1
Revises: 91fb1eb66bf2
Create Date: 2025-09-30 10:51:50.924528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e838160545c1'
down_revision = '91fb1eb66bf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'status',
               existing_type=postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='jobstatus'),
               nullable=True)
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.alter_column('jobs', 'status',
               existing_type=postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='jobstatus'),
               nullable=False)
    # ### end Alembic commands ###
