"""remove_role_column_from_users

Revision ID: fc7db2160a4f
Revises: d3c9adee8d0d
Create Date: 2025-10-02 16:18:21.860774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc7db2160a4f'
down_revision = 'd3c9adee8d0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_role_supervisor_id', table_name='users')
    op.drop_index('ix_users_role_team_id', table_name='users')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('ADMIN', name='userrole'), autoincrement=False, nullable=False))
    op.create_index('ix_users_role_team_id', 'users', ['role', 'team_id'], unique=False)
    op.create_index('ix_users_role_supervisor_id', 'users', ['role', 'supervisor_id'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    # ### end Alembic commands ###
